name: ↺ 리펙토링!
description: 기존 사항에서 개선하고 싶을 때 사용합니다.
title: "[refactor] <제목>"
labels: ["refactor"]
body:
- type: textarea
  attributes:
    label: 이슈의 SubTask들을 알려주세요.
    description: 해당 내용의 SubTask를 나열해주세요.
    placeholder: subtask1
  validations:
    required: true
